version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: $APP_UPTIME_KUMA_IP
      APP_PORT: 3001

  uptime-kuma:
    image: louislam/uptime-kuma:1.11.1@sha256:9fd26d8adae499533e0079f218b4c9139e89b3a085ec04b246c3fbf7af04aa62
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
    networks:
      default:
        ipv4_address: $APP_UPTIME_KUMA_IP